set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR AMD64)

find_program(KUE_MINGW_C_COMPILER x86_64-w64-mingw32-gcc REQUIRED)
find_program(KUE_MINGW_CXX_COMPILER x86_64-w64-mingw32-g++ REQUIRED)
find_program(KUE_MINGW_RC_COMPILER x86_64-w64-mingw32-windres REQUIRED)
set(CMAKE_C_COMPILER "${KUE_MINGW_C_COMPILER}")
set(CMAKE_CXX_COMPILER "${KUE_MINGW_CXX_COMPILER}")
set(CMAKE_RC_COMPILER "${KUE_MINGW_RC_COMPILER}")

find_program(KUE_WINE_EMULATOR wine)
if(KUE_WINE_EMULATOR)
  set(CMAKE_CROSSCOMPILING_EMULATOR "${KUE_WINE_EMULATOR}")
endif()
